"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact', # Adicionado após criação do app contact com $ python .\manage.py startapp contact
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'base_templates' # Adicionado pós criação da base_templates na raiz
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Adicionado pós criação da base_static na raiz
STATICFILES_DIRS = (
    BASE_DIR / 'base_static',
)

# Define o diretório absoluto no sistema de arquivos onde o Django irá reunir todos os 
# arquivos estáticos (CSS, JavaScript, imagens do layout) do projeto e de seus apps.
# POR QUE USAR: É obrigatório para o ambiente de produção. Ao executar o comando 
# 'python manage.py collectstatic', o Django copia os arquivos de todas as aplicações 
# para esta pasta única, facilitando para um servidor web (como Nginx ou Apache) 
# servir esses arquivos de forma rápida e segura, sem sobrecarregar o Django.
# Adicionado para a pasta static ser criada para collectstatic
STATIC_ROOT = BASE_DIR / 'static' # collectstatic

# Define o prefixo da URL que o navegador usará para acessar os arquivos de mídia.
# POR QUE USAR: Diferente dos arquivos estáticos do sistema (CSS/JS), a mídia engloba 
# os arquivos enviados ativamente pelos usuários (como fotos de perfil ou documentos). 
# Essa constante diz ao Django qual caminho textual colocar na URL (ex: ://site.com) 
# para diferenciar esses uploads públicos de outras rotas da aplicação.
# Adicionado para arquivos de images
MEDIA_URL = 'media/' # Arquivos enviados pelo usuário

# Define o caminho absoluto no disco rígido do servidor onde o Django vai salvar fisicamente 
# todos os arquivos e imagens que forem enviados (uploaded) pelos usuários do sistema.
# POR QUE USAR: Enquanto o 'MEDIA_URL' cuida apenas do endereço de internet que o navegador 
# digita, o 'MEDIA_ROOT' localiza a pasta real dentro do seu computador ou servidor (ex: C:/projeto/media/). 
# Sem essa configuração, o Django não sabe em qual pasta do sistema operacional ele deve gravar os 
# arquivos quando um formulário de upload ou campo 'ImageField' for processado.
MEDIA_ROOT = BASE_DIR / 'media'

# Define o tipo de campo padrão que o Django usará para gerar as chaves primárias (IDs) 
# automáticas de novos models que não declaram um ID próprio.
# POR QUE USAR: O 'BigAutoField' utiliza um inteiro de 64 bits (de 1 a 9 quintilhões). 
# Ele substituiu o antigo 'AutoField' (32 bits, limite de 2 bilhões) para evitar 
# que o banco de dados trave por falta de números disponíveis caso o seu sistema 
# cresça muito e gere um volume massivo de registros ao longo do tempo.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    # Tenta importar todas as variáveis de um arquivo chamado 'local_settings.py'
    # Se o arquivo existir, as configurações dele substituem as deste arquivo (settings.py)
    from project.local_settings import *
except ImportError:
    ...
    # Se o arquivo 'local_settings.py' não for encontrado, o Django ignora o erro
    # O código continua rodando normalmente com as configurações padrão
